accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register_user/', views.register_user, name='register_user'),
    path('activate/<uid_b64>/<token>/', views.user_activate, name='user_activate'),
    path('forget_password/', views.forget_password, name='forget_password'),
    path('validate_reset_password/<uid_b64>/<token>/', views.validate_reset_password, name='validate_reset_password'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('change_email/', views.change_email, name='change_email'),
    path('change_email_confirm/<uid_b64>/<token>/', views.change_email_confirm, name='change_email_confirm'),
    path('change_email_success/', views.change_email_success, name='change_email_success'),
]

csvapp/urls.py
from django.urls import path
from . import views

app_name = 'csvapp'
urlpatterns = [
    path('import', views.csv_import, name='csv_import'),
    path('export', views.csv_export, name='csv_export'),
]

mysite_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('zukan/', include('zukan.urls')),
    path('csvapp/', include('csvapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zukan/urls.py
from django.urls import path
from . import views

app_name = 'zukan'
urlpatterns = [
    path('<slug:category_slug>/index/', views.index, name='index'),
    path('<slug:category_slug>/<slug:slug>/', views.detail, name='detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <a href="{% url 'home' %}">HOME</a>
        <a href="{% url 'accounts:register_user' %}">Sign up</a>
        <a href="{% url 'accounts:login' %}">Login</a>
        <a href="{% url 'accounts:logout' %}">Logout</a>
        <a href="{% url 'accounts:forget_password' %}">Forget Password</a>
        <a href="{% url 'accounts:change_email' %}">Change Email</a>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Home Page</h1>
{% if user.is_authenticated %}
<h2>You have already logged in.</h2>
<p>{{ user }}</p>
{% endif %}
<hr>
<h2>Zukan</h2>
<ul>
    <li><a href="{% url 'zukan:index' 'dog' %}">Dog Zukan</a></li>
    <li><a href="{% url 'zukan:index' 'cat' %}">Cat Zukan</a></li>
</ul>
<hr>
<h2>CSV App</h2>
<ul>
    <li><a href="{% url 'csvapp:csv_import' %}">CSV import page</a></li>
    <li><a href="{% url 'csvapp:csv_export' %}">CSV export page</a></li>
</ul>
{% endblock %}